/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StudyRoom(props) {
  const { nodes, materials } = useGLTF('/Models/Writting Nurse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Desk_Elements"
        castShadow
        receiveShadow
        geometry={nodes.Desk_Elements.geometry}
        material={materials['Standard white.001']}
        position={[25.098, -0.183, 11.859]}
      />
      <mesh
        name="Board002"
        castShadow
        receiveShadow
        geometry={nodes.Board002.geometry}
        material={materials['Standard white.001']}
        position={[24.196, -0.183, 11.869]}
      />
      <mesh
        name="Board001"
        castShadow
        receiveShadow
        geometry={nodes.Board001.geometry}
        material={materials['Standard Black.001']}
        position={[25.098, -0.183, 11.859]}
      />
      <mesh
        name="Board"
        castShadow
        receiveShadow
        geometry={nodes.Board.geometry}
        material={materials['Material.001']}
        position={[25.098, -0.183, 11.859]}
      />
      <group
        name="Cylinder009_Metal002_0"
        position={[0.725, 1.804, 0.684]}
        rotation={[0.222, -1.49, 0.241]}
        scale={0.13}>
        <mesh
          name="Cylinder009_Metal002_0001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_Metal002_0001.geometry}
          material={materials['Metal.001']}
        />
        <mesh
          name="Cylinder009_Metal002_0001_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_Metal002_0001_1.geometry}
          material={materials['BlackPlastic.002']}
        />
      </group>
      <group
        name="Cylinder004_WhitePlastic_0"
        position={[0.191, 1.791, 1.015]}
        rotation={[0.131, -1.501, 0.097]}
        scale={0.06}>
        <mesh
          name="Cylinder004_WhitePlastic_0_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_WhitePlastic_0_1.geometry}
          material={materials.Lines}
        />
        <mesh
          name="Cylinder004_WhitePlastic_0_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_WhitePlastic_0_2.geometry}
          material={materials.WhitePlastic}
        />
        <mesh
          name="Cylinder004_WhitePlastic_0_3"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_WhitePlastic_0_3.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          name="Cylinder004_WhitePlastic_0_4"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_WhitePlastic_0_4.geometry}
          material={materials.GreenPlastic}
        />
        <mesh
          name="Cylinder004_WhitePlastic_0_5"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_WhitePlastic_0_5.geometry}
          material={materials['Metal.003']}
        />
      </group>
      <mesh
        name="Shirt_default1_0001"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0001.geometry}
        material={materials['Torso.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0002"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0002.geometry}
        material={materials['Hair1.002']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0003"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0003.geometry}
        material={materials['Face.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0004"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0004.geometry}
        material={materials['Arms.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0005"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0005.geometry}
        material={materials['sole2.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0006"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0006.geometry}
        material={materials['Material.009']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0007"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0007.geometry}
        material={materials['Material.002']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0008"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0008.geometry}
        material={materials['upper.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0009"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0009.geometry}
        material={materials['Eyelashes.002']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0013"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0013.geometry}
        material={materials['tubemetal1.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0014"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0014.geometry}
        material={materials['drumplastic.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0059"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0059.geometry}
        material={materials['Button.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0061"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0061.geometry}
        material={materials['Teeth.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0062"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0062.geometry}
        material={materials['EyeMoisture.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0065"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0065.geometry}
        material={materials['Lips.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0066"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0066.geometry}
        material={materials['Sclera.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0072"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0072.geometry}
        material={materials['Toenails.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0076"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0076.geometry}
        material={materials['drummetal1.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0078"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0078.geometry}
        material={materials['Cornea.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0082"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0082.geometry}
        material={materials['material.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <mesh
        name="Shirt_default1_0083"
        castShadow
        receiveShadow
        geometry={nodes.Shirt_default1_0083.geometry}
        material={materials['membrane1.003']}
        position={[1.31, 0.492, 1.335]}
        rotation={[0, -1.488, 0]}
        scale={0.017}
      />
      <group
        name="Cylinder002_Metal_0001"
        position={[0.022, 1.877, 1.135]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.062}>
        <mesh
          name="Cylinder002_Metal_0001_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_1.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Cylinder002_Metal_0001_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_2.geometry}
          material={materials.Vaccine}
        />
        <mesh
          name="Cylinder002_Metal_0001_3"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_3.geometry}
          material={materials.Glass}
        />
      </group>
      <group
        name="Cylinder002_Metal_0002"
        position={[-0.059, 1.877, 1.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.062}>
        <mesh
          name="Cylinder002_Metal_0001_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_1.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Cylinder002_Metal_0001_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_2.geometry}
          material={materials.Vaccine}
        />
        <mesh
          name="Cylinder002_Metal_0001_3"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Metal_0001_3.geometry}
          material={materials.Glass}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Writting Nurse.glb')
