/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NurseWithBaby(props) {
  const { nodes, materials } = useGLTF("/Models/Baby with Nurse.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Bed_low_Baby_bed_mat_0001"
        castShadow
        receiveShadow
        geometry={nodes.Bed_low_Baby_bed_mat_0001.geometry}
        material={materials["Baby_bed_mat.002"]}
        position={[-2.164, 1.261, 10.92]}
        rotation={[Math.PI, -0.026, Math.PI]}
        scale={[0.009, 0.005, 0.008]}
      />
      <mesh
        name="BabyLunaDiaper041"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper041.geometry}
        material={materials["Fingernails.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper041.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper041.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper042"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper042.geometry}
        material={materials["drumplastic.001"]}
        morphTargetDictionary={nodes.BabyLunaDiaper042.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper042.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper043"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper043.geometry}
        material={materials["MetalPins.001"]}
        morphTargetDictionary={nodes.BabyLunaDiaper043.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper043.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper044"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper044.geometry}
        material={materials["PinCaps.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper044.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper044.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper045"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper045.geometry}
        material={materials["Diaper.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper045.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper045.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper046"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper046.geometry}
        material={materials["Std_Eye_L.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper046.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper046.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper047"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper047.geometry}
        material={materials["Std_Skin_Head.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper047.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper047.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper048"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper048.geometry}
        material={materials["Std_Skin_Body.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper048.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper048.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper049"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper049.geometry}
        material={materials["Std_Skin_Arm.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper049.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper049.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper050"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper050.geometry}
        material={materials["Std_Skin_Leg.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper050.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper050.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper051"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper051.geometry}
        material={materials["Std_Eye_L.001"]}
        morphTargetDictionary={nodes.BabyLunaDiaper051.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper051.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper052"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper052.geometry}
        material={materials["Material.003"]}
        morphTargetDictionary={nodes.BabyLunaDiaper052.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper052.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper053"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper053.geometry}
        material={materials["Mouth.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper053.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper053.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper054"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper054.geometry}
        material={materials["EyeMoisture.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper054.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper054.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper055"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper055.geometry}
        material={materials["EyeSocket.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper055.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper055.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper056"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper056.geometry}
        material={materials["Legs.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper056.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper056.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper057"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper057.geometry}
        material={materials["Irises.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper057.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper057.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper058"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper058.geometry}
        material={materials["EyeSocket.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper058.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper058.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper059"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper059.geometry}
        material={materials["Irises.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper059.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper059.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper060"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper060.geometry}
        material={materials["Mouth.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper060.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper060.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper061"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper061.geometry}
        material={materials["EyeSocket.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper061.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper061.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper062"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper062.geometry}
        material={materials["EyeSocket.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper062.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper062.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper063"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper063.geometry}
        material={materials["Irises.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper063.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper063.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper064"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper064.geometry}
        material={materials["Cornea.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper064.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper064.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper065"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper065.geometry}
        material={materials["Torso.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper065.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper065.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper066"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper066.geometry}
        material={materials.Eyelashes}
        morphTargetDictionary={nodes.BabyLunaDiaper066.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper066.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper067"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper067.geometry}
        material={materials["membrane1.001"]}
        morphTargetDictionary={nodes.BabyLunaDiaper067.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper067.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper068"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper068.geometry}
        material={materials.drummetal1}
        morphTargetDictionary={nodes.BabyLunaDiaper068.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper068.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper069"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper069.geometry}
        material={materials.tubemetal1}
        morphTargetDictionary={nodes.BabyLunaDiaper069.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper069.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper070"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper070.geometry}
        material={materials.Hair1}
        morphTargetDictionary={nodes.BabyLunaDiaper070.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper070.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper071"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper071.geometry}
        material={materials["Material.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper071.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper071.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper072"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper072.geometry}
        material={materials["Fingernails.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper072.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper072.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper073"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper073.geometry}
        material={materials["sole_line.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper073.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper073.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper074"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper074.geometry}
        material={materials["sole_line.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper074.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper074.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
      <mesh
        name="BabyLunaDiaper075"
        castShadow
        receiveShadow
        geometry={nodes.BabyLunaDiaper075.geometry}
        material={materials["sole_line.002"]}
        morphTargetDictionary={nodes.BabyLunaDiaper075.morphTargetDictionary}
        morphTargetInfluences={nodes.BabyLunaDiaper075.morphTargetInfluences}
        position={[-2.412, 1.097, 10.912]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={0.011}
      />
    </group>
  );
}

useGLTF.preload("/Models/Baby with Nurse.glb");
