/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StudingNurse(props) {
  const { nodes, materials } = useGLTF('/Models/Studing_Nurse.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Shirt_default1_0001"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0001.geometry}
          material={materials['Torso.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0002"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0002.geometry}
          material={materials['Hair1.002']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0003"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0003.geometry}
          material={materials['Face.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0004"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0004.geometry}
          material={materials['Arms.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0005"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0005.geometry}
          material={materials['sole2.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0006"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0006.geometry}
          material={materials['Material.009']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0007"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0007.geometry}
          material={materials['Material.008']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0008"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0008.geometry}
          material={materials['upper.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0009"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0009.geometry}
          material={materials['Eyelashes.002']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0013"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0013.geometry}
          material={materials['tubemetal1.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0014"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0014.geometry}
          material={materials['drumplastic.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0059"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0059.geometry}
          material={materials['Button.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0061"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0061.geometry}
          material={materials['Teeth.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0062"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0062.geometry}
          material={materials['EyeMoisture.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0065"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0065.geometry}
          material={materials['Lips.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0066"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0066.geometry}
          material={materials['Sclera.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0072"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0072.geometry}
          material={materials['Toenails.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0076"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0076.geometry}
          material={materials['drummetal1.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0078"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0078.geometry}
          material={materials['Cornea.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0082"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0082.geometry}
          material={materials['material.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
        <mesh
          name="Shirt_default1_0083"
          castShadow
          receiveShadow
          geometry={nodes.Shirt_default1_0083.geometry}
          material={materials['membrane1.003']}
          position={[1.31, 0.492, 1.335]}
          rotation={[0, -1.488, 0]}
          scale={0.017}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Studing_Nurse.glb')
